makefile update

diff --git a/cmd/template/framework/files/makefile.tmpl b/cmd/template/framework/files/makefile.tmpl
--- a/cmd/template/framework/files/makefile.tmpl
+++ b/cmd/template/framework/files/makefile.tmpl
@@ -3,17 +3,47 @@
 # Build the application
 all: build
 
-build:
+{{- if and (or .AdvancedOptions.htmx .AdvancedOptions.tailwind) .OSCheck.UnixBased }}
+templ-install:
+	@if ! command -v templ > /dev/null; then \
+		read -p "Go's 'templ' is not installed on your machine. Do you want to install it? [Y/n] " choice; \
+		if [ "$$choice" != "n" ] && [ "$$choice" != "N" ]; then \
+			go install github.com/a-h/templ/cmd/templ@latest; \
+			if [ ! -x "$$(command -v templ)" ]; then \
+				echo "templ installation failed. Exiting..."; \
+				exit 1; \
+			fi; \
+		else \
+			echo "You chose not to install templ. Exiting..."; \
+			exit 1; \
+		fi; \
+	fi
+{{- end }}
+
+{{- if .AdvancedOptions.tailwind}}
+{{- if .OSCheck.UnixBased}}
+tailwind:
+	{{ if .OSCheck.linux }}@curl -sL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -o tailwindcss{{- end }}
+	{{ if .OSCheck.darwin }}@curl -sL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-x64 -o tailwindcss{{- end }}
+	@chmod +x tailwindcss
+{{- else }}
+tailwind:
+	@curl -sL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-windows-x64 -o tailwindcss
+{{- end }}
+{{- end }}
+
+build:{{- if .AdvancedOptions.tailwind }} tailwind{{- end }}{{- if and (or .AdvancedOptions.htmx .AdvancedOptions.tailwind) .OSCheck.UnixBased }} templ-install{{- end }}
 	@echo "Building..."
-	{{if or ( .AdvancedOptions.htmx ) ( .AdvancedOptions.tailwind )}}@templ generate{{end}}
-	{{if .AdvancedOptions.tailwind}}@tailwindcss -i cmd/web/assets/css/input.css -o cmd/web/assets/css/output.css{{end}}
-	{{if .UnixBased }}@go build -o main cmd/api/main.go{{ else }}@go build -o main.exe cmd/api/main.go{{ end }}
+	{{ if or .AdvancedOptions.htmx .AdvancedOptions.tailwind }}@templ generate{{- end }}
+	{{ if .AdvancedOptions.tailwind }}@./tailwindcss -i cmd/web/assets/css/input.css -o cmd/web/assets/css/output.css{{- end }}
+	{{ if .OSCheck.UnixBased }}@go build -o main cmd/api/main.go{{- else }}@go build -o main.exe cmd/api/main.go{{- end }}
 
 # Run the application
 run:
 	@go run cmd/api/main.go
 
-{{if and (ne .DBDriver "none") (ne .DBDriver "sqlite")}}
+{{- if and (ne .DBDriver "none") (ne .DBDriver "sqlite") }}
+{{- if .OSCheck.UnixBased }}
 # Create DB container
 docker-run:
 	@if docker compose up 2>/dev/null; then \
@@ -31,19 +61,28 @@ docker-down:
 		echo "Falling back to Docker Compose V1"; \
 		docker-compose down; \
 	fi
-{{end}}
+{{- else }}
+# Create DB container
+docker-run:
+	@docker compose up
+
+# Shutdown DB container
+docker-down:
+	@docker compose down
+{{- end }}
+{{- end }}
 
 # Test the application
 test:
 	@echo "Testing..."
 	@go test ./... -v
 
-{{if and (ne .DBDriver "none") (ne .DBDriver "sqlite")}}
+{{- if and (ne .DBDriver "none") (ne .DBDriver "sqlite") }}
 # Integrations Tests for the application
 itest:
 	@echo "Running integration tests..."
 	@go test ./internal/database -v
-{{end}}
+{{- end }}
 
 # Clean the binary
 clean:
@@ -51,7 +90,7 @@ clean:
 	@rm -f main
 
 # Live Reload
-{{if .UnixBased}}
+{{- if .OSCheck.UnixBased }}
 watch:
 	@if command -v air > /dev/null; then \
             air; \
@@ -67,9 +106,9 @@ watch:
                 exit 1; \
             fi; \
         fi
-{{else}}
+{{- else }}
 watch:
 	@air
-{{end}}
+{{- end }}
 
-.PHONY: all build run test clean watch
+.PHONY: all build run test clean watch{{- if .AdvancedOptions.tailwind }} tailwind{{- end }}{{- if and (ne .DBDriver "none") (ne .DBDriver "sqlite") }} docker-run docker-down itest{{- end }}{{- if and (or .AdvancedOptions.htmx .AdvancedOptions.tailwind) .OSCheck.UnixBased }} templ-install{{- end }}
